### ISSUE TITLE
分库分表：ShardingSelector 实现

### ISSUE THREAD

**Issue by flycash** [ecodeclub/eorm#143]
**仅限中文**

### 使用场景

这个作为初步实现，用来验证我们的设计。根据我们讨论的内容，ShardingSelector 牵涉到：
- 改写 SQL：目前的话我们可以假设只会有 sharding_key = ? 这种形式，如果没有 sharding_key，我们将返回错误，而不是执行广播；
- 执行 SQL：直接发起发起查询。但是对于 Get 和 GetMulti 来讲是有点区别，如果是 Get，那么我们要确保前面的改写 SQL 只能生成一个 SQL（目前加上这种严苛的校验）；如果是 GelMulti，那么就需要开启 goroutine 并发查询不同的物理表
- 合并结果集：可以复用 merger 里面批量查询

所以很显然：
- 你要考虑怎么允许用户配置分库分表规则，这部分我们目前的想法是加入进去模型元数据里面，所以你需要小心设计接口；
- 用户必须主动调用 registry.Register 方法来注册模型，指定分库分表的规则。目前我们不打算支持在 eorm 标签里面使用表达式；

依赖于 #140

**Comment by Stone-afk** [comment]
我想，或许不用用户显示的制定分库分表规则，暴露一个option就可以了，例如
```
func NewShardingSelector[T any](metaOpts ...model.TableMetaOption) *ShardingSelector[T] {
	return &ShardingSelector[T]{
		builder: builder{
			buffer: bytebufferpool.Get(),
		},
		metaOptions: metaOpts,
	}
}

func (s *ShardingSelector[T]) Build() ([]*ShardingQuery, error) {
	if s.meta == nil {
		var err error
		s.meta, err = s.metaRegistry.Get(new(T))
		if err != nil {
			return nil, err
		}
		for _, opt := range s.metaOptions {
			opt(s.meta)
		}
	}
        .......
}
```
