### ISSUE TITLE
分库分表：Datasource 抽象

### ISSUE THREAD

**Issue by flycash** [ecodeclub/eorm#164]
## 设计
在前面的 #157 里面我提到了 Datasource 抽象。它主要是为了提供一个统一的对数据源的抽象的。

基本上我们可以预期到，在实际中存在的 Datasource 会有多种可能：
- 简单的单一数据库 
- 主从集群
- 主从集群 + 对应的影子集群

如果我们进一步从逻辑上考虑，那么分库分表也可以认为是一个 Datasource，而后在其内部根据选中的集群、库和表进行分发。

此外，我们可以预期这些不同的 Datasource 是可以进行组合的。假如说我们有一个叫做 ShardingDatasource 的东西，那么我们可以预期，它内部可以包含多个主从集群，那么每个主从集群本身就是一个主库叠加多个从库这种简单的单一数据库。

更进一步说，在压力测试经常讲的影子库影子表也可以进一步被组合进去。

我们可以给 Datasource 提供一个统一的定义：
```go
type Datasource interface {
	Query(ctx context.Context, query ShardingQuery) (*sql.Rows, error)
	Exec(ctx context.Context, query ShardingQuery) (sql.Result, error)
}
```
其中 ShardingQuery 定义为：
```go
type ShardingQuery struct {
	SQL  string
	Args       []any
	Datasource string
}
```

这种设计有一个很明显的缺陷，就是 query 本身被限定为和 Datasource 有关的概念了。

### ShardingDatasource
可以定义为：
```go
type ShardingDatasource struct {
	datasources map[string]Datasource
}

func (s *ShardingDatasource) Query(ctx context.Context, query ShardingQuery) (*sql.Rows, error) {
	ds, ok := s.datasources[query.Datasource]
	if !ok {
		return nil, errors.New("datasource not found")
	}
	return ds.Query(ctx, query)
}

func (s *ShardingDatasource) Exec(ctx context.Context, query ShardingQuery) (sql.Result, error) {
	//TODO implement me
	panic("implement me")
}
```
那么很显然，ShardingDatasource 一点都不关心具体的一个 Datasource 究竟是单一的 DB，还是一个主从结构，还是说混合了影子库影子表的东西。

### MasterSlavesDatasource
对于主从数据源来说，可以定义为：
```go
type MasterSlavesDatasource struct {
	master *sql.DB
	slaves slaves.Slaves
	core
}
```
注意这里值得斟酌的是 master，可以考虑将类型从 sql.DB 换成 Datasource 本身，那么就可以层层嵌套，形成类似于千层饼的结构了。

### 影子库和影子表的支持
理论上来说，影子表只能从分库分表规则里面在生成的 SQL 里面将表名换成影子表名。

但是如果是影子库，那么其实有很多种做法，可以考虑定义一个全新的 ShadowDatasource，里面维持住 live 和 shadow 两个 Datasource
```go
type ShadowDatasource struct {
	live   Datasource
	shadow Datasource
}
```

那么也可以考虑说增强我们前面的的 MasterSlavesDatasource，在里面嵌入一个 shadow 的字段：
```go
type MasterSlavesDatasource struct {
	master *sql.DB
	slaves slaves.Slaves
	shadow Datasource
}
```
当然，在 ShardingDatasource 里面增加一个 shadows 字段也不是不可以。

所以本质上，shadow 还是非 shadow，并不是分库分表内核需要管理的东西。

### zone 支持

简单来说，可以认为一个 zone 就是一个 Datasource 实例，而后多个 zone 对应的 Datasource 可以合并在一起构成一个业务上有意义的单位。

比如说订单表，那么可能有中国 zone，可能有美国 zone，那么分库分表无非就是要确认某一个请求是发给美国 zone 还是发给中国 zone。

当然，如果是彻底的隔离机制，那么我们可以做到说，在初始化 zone 所代表的 Datasource时，我们只初始化所在 zone 的那个实例。

而不管如何，这些事情都可以被限制在 Datasource 的某一个实现之类。依旧可以确保说整个分库分表的核心是和 zone 没有什么关系的。

### 已有的 Session 概念
不得不说，这是我借鉴得非常失败的一个概念。本身源自某 ORM 框架的概念，但是现在我看来，Session 应该被 Datasource 取代。

之前是顾虑到有一类场景，用户可能希望把一些的操作放在一个上下文内，在这个上下文内他们可以考虑设置一些共享的设置，比如说链接参数、ORM 的 middleware 等。

但是现在看起来，完全没有这个必要。

接下来我们还会保留这个 Session 概念，但是会进一步淡化它的作用。

**Comment by Stone-afk** [comment]
主从集群怎么定义的，按照传统的定义，咱们缺一个集群的实现，目前框架的 masterSlave 缺一个集群的实现

**Comment by Stone-afk** [comment]
主从集群怎么定义的，按照传统的定义，目前框架的 masterSlave 缺一个集群的实现

**Comment by Stone-afk** [comment]
这里偏向于增加 clusterDB 的实现，而 MasterSlavesDatasource 已经和 MasterSlavesDB 重复，我觉得用 DB 作为具体实现 和 ShardingDatasource 去实现 Datasource，而 ShardingDatasource 里保存的一样可以是  Datasource 的具体实现包括 clusterDB、MasterSlavesDB 等，它们都实现了 Datasource

**Comment by Stone-afk** [comment]
‘’‘
m := map[string]*MasterSlavesDB{
		"order_db_0": masterSlaveMemoryDB(),
		"order_db_1": masterSlaveMemoryDB(),
		"order_db_2": masterSlaveMemoryDB(),
	}
	clusterDB := OpenClusterDB(m)
	ds := map[string]sharding.DataSource{
	"0.db.cluster.company.com:3306": clusterDB,
	"1.db.cluster.company.com:3306": clusterDB,
}

’‘’

**Comment by Stone-afk** [comment]
这里 ClusterDB 其实就是  Datasource 的实现了，ClusterDB Set 方法的意义在于给 ClusterDB 增加 masterSlave DB

**Comment by flycash** [comment]
这里可能还有一个地方是值得讨论的。假如说，我有两个库，user_db_0 和 user_db_1 实际上都部署在同一个主从集群上。那么，MasterSlavesDB 应该是两个，还是一个？

**Comment by Stone-afk** [comment]
对，我实际上就是这个意思，这是我几天之前的留言=.=

**Comment by Stone-afk** [comment]
肯定是两个 masterslave db，因为你看sql.DB的连接，是包含库名的

**Comment by flycash** [comment]
> 肯定是两个 masterslave db，因为你看sql.DB的连接，是包含库名的，所以才会考虑增加 cluster db

还真不一定。我们生成的 SQL 里面天然就带了库名。我举个例子，如果你有两个库 user_db_0和user_db_1，而且你有一个数据库用户 my_business 对两个 user_db_0, user_db_1 都有权限，那么你完全可以在链接信息里面用 user_db_0，但是查询用的是 user_db_1.user_tab。

那么问题来了，我们进一步捋清楚：$region.mysql.business.com:3306/user_db_$user_id%3。假如 region 取值有两个，cn 和 tw，那么你会有几个主从？

**Comment by Stone-afk** [comment]
如果 datasoure name 为库名时，就会出现你说的问题，我的理解是 region 的取值只决定 cluster 的个数，貌似决定不了库的个数，$region.mysql.business.com:3306 应当看作一个 cluster吧，如果 $region.mysql.business.com:3306/user_db_$user_id%3 整个都按 一个库的 name 计算的话 那会有 cn * tw * 3 个主从

**Comment by flycash** [comment]
那这样的话，这三个实现就够了。其中 MasterSlavesDB 完全看用户怎么用了。如果用户注册一个 cn_user_1 那么就是 cn.mysql.business.com:3306/user_db_1。

但是用户也完全可以就注册一个 cn，代表的是cn.mysql.business.com:3306/user_db_1，但是我们也可以在自己的查询语句里面带上 user_db_2.user_tab。

这完全取决于用户的想法，以及用户使用 mysql 账号和权限的问题。

**Comment by flycash** [comment]
并不是你说的这种使用形式，而是：
```
m := map[string]*MasterSlavesDB{
"order_cn": masterSlaveMemoryDB(),
}

}
```
固定返回 order cn。order_cn 上面可以有多个逻辑上的 DB，就是 `create database` 创建出来的。那么查询语句里面，带上 order_db_0，那就是查询 db_0。当然，前提是 DSN 里面的用户是有权限的。

你这种用法确实是我希望用户使用的用法。但是也有缺陷，就是会需要额外的连接。比如说现在就是 order_db_0, 和 order_db_1 各一个，但是实际上这两个都在同一个节点上

**Comment by Stone-afk** [comment]
那这是要引入连接管理功能？因为看起来只有查询得时候，才能建立连接

**Comment by Stone-afk** [comment]
后面这个 cn 和 cn.mysql.business.com:3306 是不是同步的， cn.mysql.business.com:3306 集群里的库是不是都以 cn 为结尾？

**Comment by flycash** [comment]
不是，而是说我实际上就两个 cn.mysql.business.com:3306 和 tw.mysql.business.com:3306 主从集群。而这每一个集群上都分别有三个逻辑数据库，user_db_0 这种。那么用户其实完全可以只注册两个 MasterSlavesDB，比如说 root:root@tcp(cn.mysql.business.com:3306)/user_db_aaaa，然后因为 root 本身对 user_db_0,1,2 都有权限，所以它可以只判断你的查询语句是给 CN 还是给 TW，来决定这个主从集群。

**Comment by flycash** [comment]
#170
