### ISSUE TITLE
 BasicTypeValue重命名建议

### ISSUE THREAD

**Issue by flyhigher139** [ecodeclub/eorm#176]
**仅限中文**

### 使用场景

eorm valuer包里的BasicTypeValuer，相关代码文件和代码中的结构体、函数命名，都是XXXbasicXXX形式，比较容易误导人理解为这是一个功能不是很完善的基础valuer，但这实际上是一个支持了基础类型的增强型valuer

所以，这个valuer的命名是不是可以改一下，比如`advancedValuer`, `extendedValuer`, `enhancedValuer` 等？

### 行业分析
> 如果你知道有框架提供了类似功能，可以在这里描述，并且给出文档或者例子

### 可行方案
> 如果你有设计思路或者解决方案，请在这里提供。你可以提供多个方案，并且给出自己的选择

### 其它
> 任何你觉得有利于解决问题的补充说明

### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flycash** [comment]
好问题，但是我觉得你提议的名字也不是很好。 BasicTypeValuer 是一个临时产物，我也想换名字，但是找不到合适的。

**Comment by flycash** [comment]
advancedValuer, extendedValuer, enhancedValuer 这三个名字，约等于没说。因为看上去你不知道什么才是 advanced，或者说 enhance 了什么

**Comment by flyhigher139** [comment]
那PrimitiveValuer是不是比BasicTypeValuer看上去更专业一点？ 😃

**Comment by flycash** [comment]
PrimitiveTypeEnhanceValuer?

**Comment by flycash** [comment]
相关内容 #108 #105

**Comment by flyhigher139** [comment]
> PrimitiveTypeEnhanceValuer?

我觉得Primitive足以表达基本类型的意思了
所以可以简化为PrimitiveEnhancedValuer

另外，再简洁点，就叫PrimitiveValuer，代码中加上注释，我感觉也可以。
主要是Primitive本身就对应到基础类型，有一半的概率，一看到命名就能猜到是基础类型增强的Valuer，如果不清楚PrimitiveValuer，看一眼注释说明就一目了然了

**Comment by flycash** [comment]
倒是比 BasicTypeValuer 好。你可以发一个合并请求

**Comment by flyhigher139** [comment]
好~
