### ISSUE TITLE
分库分表: ShardingInserter 的语句生成改为 Table 维度

### ISSUE THREAD

**Issue by Stone-afk** [ecodeclub/eorm#205]
目前来看，在真实的执行场景下做不到按照 DB 维度来发送请求。
有两个问题：

1、尝试使用 multiStatements=true 选项的时候，依旧会出错；
2、即便可以使用 multiStatements，也难以教会用户在这里必须要指定 multiStatements，而且 db 那块代码的设计还要在原来的基础上做改动，目前也不想我们自己拼接一个

所以改成一个表一个

**Comment by Stone-afk** [comment]
这里忽略了 ds 只考虑了 db 吧，还有是不是要考虑长事务带来的影响

**Comment by Stone-afk** [comment]
比如 造成 大量的阻塞和锁超时，主从延迟啥的

**Comment by flycash** [comment]
只考虑 DB，数据库是做不到跨 DB 事务的吧？暂时保持表维度吧，长事务我倒是没有想到的。不过这个要支持，需要先支持了分布式事务。

**Comment by Stone-afk** [comment]
“只考虑 DB，数据库是做不到跨 DB 事务的吧？” 我的意思是你的描述里忽略了 ds

**Comment by Stone-afk** [comment]
支持了分布式事务后，其实用户也可以自己手动开事务

**Comment by flycash** [comment]
这下子可怕了，我们要全部改成 DB 维度了。
