### ISSUE TITLE
为什么不在项目右侧放置官网的地址呢?

### ISSUE THREAD

**Issue by Skyenought** [ecodeclub/eorm#209]
**仅限中文**

在提之前请先查找[已有 issues](https://github.com/ecodeclub/eorm/issues)，避免重复上报。

并且确保自己已经：
- [x] 阅读过文档
- [x] 阅读过注释
- [x] 阅读过例子

### 你的问题
为什么不在项目右侧放置官网的地址呢?
没仔细看, 还以为咱们的官网只有离线版本呢😀
### 你设置的的 Go 环境?
> 上传 `go env` 的结果

**Comment by flycash** [comment]
因为那个网站还不够稳定，我是打算换一个地方放的
